#!/usr/bin/python

#   Copyright 2014 Martijn Grendelman <m@rtijn.net>
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

import sys
import gpxtools

try:
    filename = sys.argv[1]
except Exception:
    print "Usage: gpx-split <filename>"
    print "Split tracks from <filename> to individual files"
    sys.exit(1)

gpxtools.split(filename)

# vim: ts=4 sw=4 et :
