#!/usr/bin/python

import sys
import gpxtools

try:
    filename = sys.argv[1]
except Exception:
    print "Usage: gpx-split <filename>"
    print "Split tracks from <filename> to individual files"
    sys.exit(1)

gpxtools.split(filename)

# vim: ts=4 sw=4 et :
