#!/usr/bin/python

#   Copyright 2014 Martijn Grendelman <m@rtijn.net>
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

import sys
import gpxtools

try:
    file1 = sys.argv[1]
    file2 = sys.argv[2]
except Exception:
    print "Usage: gpx-merge <file1> <file2>"
    print "Merge <file2> into <file1> and optionally delete <file2>"
    sys.exit(1)

gpxtools.merge(file1, file2)
